### ISSUE TITLE
SPM support

### ISSUE THREAD

**Issue by zelenizub** [supertokens/supertokens-ios#46]
Hi! Could you maybe provide Swift Package Manager support? Thanks in advance.

**Comment by nkshah2** [comment]
Hi @zelenizub 

Thanks for the issue. SPM support is something that is in the pipeline but we cannot speak for when this will be picked up because other tasks take priority at the moment. Ill leave this issue open for the time being so that you and other interested users can use this as a way to track progress on this

**Comment by nkshah2** [comment]
Hey @zelenizub 

Support for SPM was added with https://github.com/supertokens/supertokens-ios/pull/48 and is available for use from version 0.2.5. Closing this issue, feel free to reopen if you face issues
